#!/usr/bin/env sh

BASE_DIR=$(dirname "$(readlink -f "$0")")
REPO_PATH=$(readlink -f .)
REPO_NAME=$(basename "$REPO_PATH")

while read oldrev newrev ref; do
    BRANCH=$(basename "$ref")
    "$BASE_DIR/GDC.pl" "$BRANCH" "$REPO_NAME" | tee /tmp/sam.log
done

exec git update-server-info

