#!/usr/bin/env sh

BASE_DIR=$(dirname "$(readlink -f "$0")")
REPO_PATH=$(readlink -f .)
REPO_NAME=$(basename "$REPO_PATH")

while read oldrev newrev ref; do
    BRANCH=$(basename "$ref")
    if echo "$newrev" | egrep -q '^0+$'; then
        echo "Branch deletion asked, no deployment"
    else
        "$BASE_DIR/GDC.pl" "$BRANCH" "$REPO_NAME" 
    fi
done

exec git update-server-info

